export const mockedProducts = [
    {
        id: 1,
        date: "2021-02-21T20:17:26.366Z",
        name: "Arch Blick",
        img: "https://placeimg.com/640/360/any",
        sold: true,
        price: "584.00",
        brand: "Practical Steel Cheese",
        description: "Executive backing up Function-based",
        seller: "Leonor30",
        size: "M",
    },
    {
        id: 2,
        date: "2021-02-22T06:28:38.305Z",
        name: "Ms. Fiona Spencer",
        img: "https://placeimg.com/640/360/any",
        sold: true,
        price: "412.00",
        brand: "Tasty Plastic Shoes",
        description: "Lithuania",
        seller: "Ismael_Greenfelder",
        size: "S",
    },
    {
        id: 4,
        date: "2021-02-21T20:08:38.075Z",
        name: "Lindsay McLaughlin",
        img: "https://placeimg.com/640/360/any",
        sold: false,
        price: "131.00",
        brand: "Rustic Metal Towels",
        description: "technologies microchip",
        seller: "Tania.Ziemann38",
        size: "M",
    },
];
